const fs = require("fs");
const copyfiles = require("copyfiles");
const rimraf = require("rimraf");
const pkg = require("./package.json");

// Clean the build folder
rimraf.sync("./build");

// Generate version.ts from package.json
fs.writeFileSync(
  "./src/version.ts",
  `// Auto-generated by prebuild.js - do not edit\nexport const version = "${pkg.version}";\n`
);

// Copy the license file
copyfiles(["../../../LICENSE", "."], true /* flat */, () =>
  console.log("done copying license file")
);
