name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  buildandtest:
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      # Visual Studio Code Extension
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Create Python virtual env
        run: python -m venv .venv
      - name: Install Python packages (Windows)
        if: runner.os == 'Windows'
        run: |
          .venv\Scripts\activate
          pip install -r requirements.txt
      - name: Install Python packages (Linux, MacOS)
        if: runner.os != 'Windows'
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: ls project (Linux)
        if: runner.os == 'Linux'
        run: |
          ls -a
          ls -a ./.venv
          ls -a ./.venv/lib
          ls -a ./.venv/lib/python3.13
          ls -a ./.venv/lib/python3.13/site-packages
      - name: ls project (Windows)
        if: runner.os == 'Windows'
        run: |
          dir
          dir .\.venv
          dir .\.venv\lib
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - name: Setup MSVC (Windows)
        if: runner.os == 'Windows'
        uses: crazy-max/ghaction-chocolatey@v4
        with:
          args: install python visualstudio2022-workload-vctools -y
      - name: Install yarn packages
        run: yarn
      - name: Run all builds
        run: yarn build
      - name: Run Typescript tests
        run: yarn test
      - name: Run Python tests (Windows)
        if: runner.os == 'Windows'
        run: |
          .venv\Scripts\activate
          pytest
      - name: Run Python tests (Linux, MacOS)
        if: runner.os != 'Windows'
        run: |
          source .venv/bin/activate
          pytest

      # npm runtime package
      - name: Install Yarn packages
        working-directory: packages/runtime
        run: yarn
      - name: Check for matching version numbers
        working-directory: packages/runtime
        run: yarn run checkver
      - name: Build npm package
        working-directory: packages/runtime
        run: yarn build
